### PR TITLE
Prepare data

### PR DESCRIPTION
**Pull request by sanadwj**
## This PR for:
- Forking the ror-social-scaffold project
- Create relationship EDR
- Add relationship EDR to docs

### CODE REVIEW

**Comment by sanadwj** [comment]
Make another pull request as requested in the closed PR

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello! @sanadwj, @wrakc. Well done:+1: Your entities are well represented but we need to make a small change**

All the _has_many/belong\_to_ associations you have in this project should be represented with:

image

This clearly tells us that _entity one_ can have 0 or many _entity two_ and _entity two_ belongs to one and only one _entity one_

instead of 

image

_**Kindly make this change and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

**Comment by carlosveigadev** [comment]
Thanks @mosesogwo!

We updated the associations as requested.

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Pull request merged**
